---
tap_install:
  secrets:
    eso:
      vault:
        server: http://3.144.152.24:8200
        namespace: ""
        auth:
          kubernetes:
            mountPath: auto-eks-kjtsnepvfu-2
            role: auto-eks-kjtsnepvfu-2--tap-install-secrets
      remote_refs:
        tap_sensitive_values:
          sensitive_tap_values_yaml:
            key: secret/dev/auto-eks-kjtsnepvfu-2/tap/sensitive-values.yaml
